### ISSUE TITLE
Extend trading options

### ISSUE THREAD

**Issue by FoxMiner** [aloysius-pgast/crypto-exchanges-gateway#12] opened 2017-10-08 23:05 UTC
good proyect !  It plans to add more trading options  ex: trailing stop, stop limit?

**Comment by aloysius-pgast** [comment] 2017-10-30 17:05
Hi.
Sure, this is something I plan to add in a future release but it's tricky since most exchanges do not allow to track conditional orders using API, so I'll need to see how to implement the behaviour on my side (which would allow to have stop loss, trailing stop even if exchange does not support it). 
Right now I'm busy implementing real time data through websocket, but I'll look into this after

**Comment by FoxMiner** [comment] 2017-11-14 21:16
you could try to implement the library
https://github.com/ccxt/ccxt
to connect to a large volume of exchanges and get prices in real time
I could save a lot of time and develop an excellent trading dasboard

**Comment by aloysius-pgast** [comment] 2017-11-15 14:20
Thanks for the suggestion. I don't plan to implement so many exchanges for the moment. I'd rather rely on separate packages for each exchange for now. Also, I don't think ccxt provides real time data for all exchanges yet. Anyway it's a very nice project and I will probably git it a try when I implement new exchanges

**Comment by tymiles003** [comment] 2017-12-02 10:23
Team,
Any plans to implement a trading bot, most of the feature you speak can be placed there. Correct?

**Comment by aloysius-pgast** [comment] 2017-12-02 14:25
Hi. [Develop](https://github.com/aloysius-pgast/crypto-exchanges-gateway/tree/develop) branch of project already support real-time data for order book, tickers & trades (through WS endpoint). This can already be used to build simple bots. Next steps will be to try to implement stop losses and trailing stop losses in the gateway and make building bots easier. I think that when writing bots, people shouldn't have to bother to deal with the differences between exchanges and have to integrate multiple API. The gateway makes it easier because it tries to provide consistent API for multiple exchanges, through a single REST/WS endpoint. People can then just pickup whatever language they want to build a bot

**Comment by paultbarrett** [comment] 2018-01-08 11:21
Hi,

Just wanted to check if any stop loss functionality has been added yet.
Would also love to see a moving conditional take profit / stop loss function.

Example
Initial
Stop Loss - 0.005
Buy - 0.01
Target 1 - 0.02
Target 2 - 0.03
Target 3 - 0.04

Conditional
At Target 1 reached move stop loss to price x (Buy + Exchange Fees)
At Target 2 reached move stop loss to price x (Target 1) or take profit
At Target 3 reached take profit

Also would be happy to donate to the cause to see the above added. 
Do you have a ZEN address ?

**Comment by aloysius-pgast** [comment] 2018-01-08 14:18
Hi
Stop loss has not been added yet but it's definitely something I'm willing to implement. I just didn't dind the best way to do it yet. Regarding your example for target 2, what do you mean with _At Target 2 reached move stop loss to price x (Target 1) or take profit_ ?

**Comment by paultbarrett** [comment] 2018-01-09 11:18
Hi,

If we look at normal stop loss or trailing stoploss first it works as follows.
(Assuming a long and not short condition, same for both but will only explain the operation for long)

Normal stoploss is static and could be defined as a percentage but generally a fixed unit based on the actual buy price.
Example

Action | Value
------------ | ------------- 
Buy | 0.01BTC 
Stop Loss | 0.009BTC

If the market peaks to 0.05BTC my stop loss is still set to 0.009BTC

-----
Trailing stoploss is a static percentage that trails the peak market movement.
Example

Action | Value
------------ | ------------- 
Buy | 0.01BTC
Stop Loss | 10% of peak market value

Initial stoploss at the buy would be 0.009

If the market peaked to 0.05BTC then because of the trailing stop loss it would be 10% behind market peak so 0.045BTC

As you can see this is good but still not very flexible.

What i propose is to have a conditional logic for trades.
You have conditions that can be evaluated by a number of operators with associated action pairs.

Action | Condition
------------ | -------------
Buy | If <= 0.01BTC
Initial Stop Loss | 0.005BTC
Target 1 | If => 0.04BTC Then Stop Loss = Buy
Target 2 | If => 0.06BTC Then Stop Loss = Target 1
Target 3 | If => 0.08BTC Then Sell

**Comment by aloysius-pgast** [comment] 2018-01-09 17:53
Great, thanks for the detailed explanation. I'll see how we can implement such behaviour

**Comment by aloysius-pgast** [comment] 2023-11-11 22:36
Closing this since this repo is almost dead

**Comment by aloysius-pgast** [comment] 2023-11-11 22:37
Closing this since this repo is almost dead

**Closed by aloysius-pgast** 2023-11-11 22:37 UTC
Labels: enhancement
